import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { CheckCircle2, X } from 'lucide-react';

interface Sale {
  name: string;
  location: string;
}

const sales: Sale[] = [
  { name: "Luciano", location: "Macaé - RJ" },
  { name: "Sarah", location: "Ipatinga - MG" },
  { name: "Helton", location: "Rio de Janeiro - RJ" },
  { name: "João", location: "São Luís - MA" },
  { name: "Vinicius", location: "Oriximiná - PA" },
  { name: "Cleilson", location: "Parauapebas - PA" },
  { name: "Diego", location: "Conceição do Mato Dentro - MG" },
  { name: "Marcelo", location: "Jacareí - SP" },
  { name: "Valentim", location: "Lagoa Santa - MG" },
  { name: "Fabio", location: "Parauapebas - PA" },
  { name: "Raphael", location: "Matozinhos - MG" },
  { name: "Everton", location: "Cotia - SP" },
  { name: "Rafael", location: "Brumadinho - MG" },
  { name: "Reginaldo", location: "Campos dos Goytacazes - RJ" },
  { name: "Leandro", location: "Jaguariaíva - PR" },
  { name: "Juliano", location: "Campos belos - GO" },
  { name: "Rafael", location: "Vitória - ES" },
  { name: "Claudinei", location: "Cotia - SP" },
  { name: "Iago", location: "Hortolândia - SP" },
  { name: "Gabriel", location: "Indaiatuba - SP" },
  { name: "Wilkerson", location: "Rio das Ostras - RJ" },
  { name: "Thiago", location: "Campinas - SP" },
  { name: "Otavio", location: "Barretos - SP" },
  { name: "David", location: "São Vicente - SP" },
  { name: "Antônio", location: "São Luís - MA" },
  { name: "José", location: "Mineiros - GO" },
  { name: "Eduardo", location: "Rio de Janeiro - RJ" },
  { name: "Cosme", location: "Salvador - BA" },
  { name: "Julieder", location: "Itapira - SP" },
  { name: "Raimundo", location: "Oriximiná - PA" },
  { name: "Maciel", location: "Manaus - AM" },
  { name: "Irley", location: "Tailândia - PA" },
  { name: "Cristiano", location: "Nova Iguaçu - RJ" },
  { name: "Márcio", location: "Manaus - AM" },
  { name: "Rodrigo", location: "Lorena - SP" },
  { name: "Claudio", location: "Rio Claro - SP" },
  { name: "César", location: "Franca - SP" },
  { name: "Maykon", location: "Campos dos Goytacazes - RJ" },
  { name: "Walberti", location: "Araucária - PR" },
  { name: "Bernilson", location: "São Luís - MA" },
  { name: "Rodrigo", location: "São Paulo - SP" },
  { name: "Gilmar", location: "Sorocaba - SP" },
  { name: "Juan", location: "Presidente Figueiredo - AM" },
  { name: "Kleberson", location: "Cosmópolis - SP" },
  { name: "Maurício", location: "Presidente Prudente - SP" },
  { name: "Reinaldo", location: "Praia Grande - SP" },
  { name: "Douglas", location: "Santa Cruz do Rio Pardo - SP" },
  { name: "Leandro", location: "Parauapebas - PA" },
  { name: "Luis", location: "Recife - PE" },
  { name: "Pedro", location: "Belo Horizonte - MG" },
  { name: "Ivan", location: "Atibaia - SP" },
  { name: "Kleber", location: "Curitiba - PR" },
  { name: "Heron", location: "Montes Claros - MG" },
  { name: "Renato", location: "Belford Roxo - RJ" },
  { name: "Rafael", location: "Cabo Frio - RJ" },
  { name: "Cláudio", location: "Volta Redonda - RJ" },
  { name: "João", location: "Ananindeua - PA" },
  { name: "Edmundo", location: "Ilhéus - BA" },
  { name: "Fabio", location: "São Bernardo do Campo - SP" },
  { name: "Rian", location: "Alvorada de Minas - MG" },
  { name: "Cesar", location: "Candeias - BA" },
  { name: "Marcio", location: "São Luís - MA" },
  { name: "Jonatha", location: "São Luís - MA" },
  { name: "Luciene", location: "Rio de Janeiro - RJ" },
  { name: "Raphael", location: "Londrina - PR" },
  { name: "Valtair", location: "Aracruz - ES" },
  { name: "Igor", location: "Macaé - RJ" },
  { name: "Wanzeler", location: "Barroso - MG" },
  { name: "Adreir", location: "Lages - SC" },
  { name: "Anderson", location: "Sorocaba - SP" },
  { name: "Danilo", location: "Ribeirão Vermelho - MG" },
  { name: "Gabriel", location: "Sumaré - SP" },
  { name: "Felipe", location: "Belém - PA" },
  { name: "Marcos", location: "Rio de Janeiro - RJ" },
  { name: "Filipe", location: "Fraiburgo - SC" },
  { name: "Jorge", location: "Caxias do Sul - RS" },
  { name: "Alex", location: "São Bernardo do Campo - SP" },
  { name: "Renato", location: "Porto Feliz - SP" },
  { name: "Jeone", location: "Cambuci - RJ" },
  { name: "Ednaldo", location: "Bela Vista de Goiás - GO" },
  { name: "Geraldo", location: "Serranópolis - GO" },
  { name: "Marcelo", location: "Balneário Rincão - SC" },
  { name: "Iraníldo", location: "Laranjeiras - SE" },
  { name: "Antonio", location: "Queimadas - PB" },
  { name: "André", location: "Rondonópolis - MT" },
  { name: "Francisco", location: "Campinas - SP" },
  { name: "Phelipe", location: "Niterói - RJ" },
  { name: "Cleiton", location: "Belém - PA" },
  { name: "Francisco", location: "Santa Quitéria - CE" },
  { name: "Erasmo", location: "Duque de Caxias - RJ" },
  { name: "Matheus", location: "Jaboticabal - SP" },
  { name: "Guilherme", location: "Francisco Morato - SP" },
  { name: "Eduardo", location: "Parobé - RS" },
  { name: "Fernando", location: "Duque de Caxias - RJ" },
  { name: "Ismael", location: "Taquari - RS" },
  { name: "Gustavo", location: "Curitiba - PR" },
  { name: "Luís", location: "João Monlevade - MG" },
  { name: "Igor", location: "Araguari - MG" },
  { name: "Domingos", location: "Luís Eduardo Magalhães - BA" },
  { name: "Alvaro", location: "Caucaia - CE" },
  { name: "Luis", location: "Nova Iguaçu - RJ" },
  { name: "Fernando", location: "Vilhena - RO" },
  { name: "Marcos", location: "Uberlândia - MG" },
  { name: "Cleiton", location: "Colatina - ES" },
  { name: "Thiago", location: "São Paulo - SP" },
  { name: "Sergio", location: "Recife - PE" },
  { name: "Paulo", location: "Anchieta - ES" },
  { name: "Jemerson", location: "Alto Taquari - MT" },
  { name: "Silvio", location: "Serra - ES" },
  { name: "Felipe", location: "Batatais - SP" },
  { name: "Ramon", location: "São Miguel dos Campos - AL" },
  { name: "Rômulo", location: "Barra do Piraí - RJ" },
  { name: "Daniel", location: "Paragominas - PA" },
  { name: "Pedro", location: "Rio Grande - RS" },
  { name: "Eudes", location: "Tutóia - MA" },
  { name: "Lucas", location: "Itabira - MG" },
  { name: "Sidnei", location: "Belo Horizonte - MG" },
  { name: "Rovian", location: "Bento Gonçalves - RS" },
  { name: "Juan", location: "Itabira - MG" },
  { name: "Alexandre", location: "Boa Vista - RR" },
  { name: "Lucas", location: "Campestre do Maranhão - MA" },
  { name: "Andre", location: "Araxá - MG" },
  { name: "Caio", location: "Brasília - DF" },
  { name: "Gilvane", location: "Ji-Paraná - RO" },
  { name: "Matheus", location: "Campinas - SP" },
  { name: "Ítalo", location: "Campina Grande - PB" },
  { name: "Augusto", location: "Santa Rosa de Viterbo - SP" },
  { name: "Evailton", location: "Guarulhos - SP" },
  { name: "Jaecio", location: "Manaus - AM" },
  { name: "Dyeneci", location: "Duque de Caxias - RJ" },
  { name: "Noete", location: "Parauapebas - PA" },
  { name: "Ronnie", location: "Santo André - SP" },
  { name: "Edson", location: "Paiçandu - PR" },
  { name: "Genilson", location: "Dias D'Ávila - BA" },
  { name: "Savio", location: "Serra - ES" },
  { name: "Tiago", location: "Itabira - MG" },
  { name: "Andre", location: "Lençóis Paulista - SP" },
  { name: "Reginaldo", location: "Congonhas - MG" },
  { name: "Matheus", location: "Guarulhos - SP" },
  { name: "Jose", location: "Paulo Afonso - BA" },
  { name: "Luan", location: "Nova Andradina - MS" },
  { name: "Alisson", location: "Salvador - BA" },
  { name: "Elivelton", location: "Cosmópolis - SP" },
  { name: "Edson", location: "Campo Alegre - SC" },
  { name: "Wendell", location: "Itabirito - MG" },
  { name: "Glaucio", location: "Curitiba - PR" },
  { name: "Biligan", location: "Curitiba - PR" },
  { name: "Valdenor", location: "Rio Branco - AC" },
  { name: "Jeidson", location: "Catu - BA" },
  { name: "Lucas", location: "Recife - PE" },
  { name: "Raphael", location: "Telêmaco Borba - PR" },
  { name: "Moises", location: "Paranaiguara - GO" },
  { name: "Mikael", location: "Niterói - RJ" },
  { name: "George", location: "Salvador - BA" },
  { name: "Wesley", location: "Praia Grande - SP" },
  { name: "Andrey", location: "Manaus - AM" },
  { name: "Luciano", location: "Icaraíma - PR" },
  { name: "Bruno", location: "Itapeva - SP" },
  { name: "Jeandson", location: "São Francisco do Conde - BA" },
  { name: "Alex", location: "São Vicente - SP" },
  { name: "Marcos", location: "Macaé - RJ" },
  { name: "Daniel", location: "Rio de Janeiro - RJ" },
  { name: "Elias", location: "Faxinal dos Guedes - SC" },
  { name: "Antunes", location: "Fortaleza - CE" },
  { name: "Thiago", location: "Arapiraca - AL" },
  { name: "Rafael", location: "Serra - ES" },
  { name: "Alessandro", location: "São Luís - MA" },
  { name: "Aldo", location: "Simões Filho - BA" },
  { name: "Valdinei", location: "Guarapuava - PR" },
  { name: "Murilo", location: "Canaã dos Carajás - PA" },
  { name: "Thiago", location: "Serra do Salitre - MG" },
  { name: "Victor", location: "Santa Bárbara D'Oeste - SP" },
  { name: "Flavio", location: "Nova Iguaçu - RJ" },
  { name: "Cristiano", location: "Barra do Piraí - RJ" },
  { name: "Jefferson", location: "Arapoti - PR" },
  { name: "Claudio", location: "Serra - ES" },
  { name: "Diego", location: "Campos Novos - SC" },
  { name: "André", location: "Várzea da Palma - MG" },
  { name: "Joel", location: "São Luís - MA" },
  { name: "Isac", location: "Maracanaú - CE" },
  { name: "Odir", location: "Serra - ES" },
  { name: "Emerson", location: "Paracatu - MG" },
  { name: "Lucas", location: "Candeias - BA" },
  { name: "Marcos", location: "Lages - SC" },
  { name: "João", location: "Rio Pardo - RS" },
  { name: "Jessé", location: "Resende - RJ" },
  { name: "Hamilton", location: "Rio de Janeiro - RJ" },
  { name: "Dario", location: "Maricá - RJ" },
  { name: "Edson", location: "Itaguaí - RJ" },
  { name: "José", location: "Sinop - MT" },
  { name: "Lucas", location: "Cabo Frio - RJ" },
  { name: "Josenildo", location: "Candeias - BA" },
  { name: "Lucas", location: "Conceição da Feira - BA" },
  { name: "Matheus", location: "Americana - SP" },
  { name: "Raimundo", location: "Candeias - BA" },
  { name: "Hygor", location: "Ponta Grossa - PR" },
  { name: "Elvis", location: "Itapetininga - SP" },
  { name: "Ricardo", location: "Petrópolis - RJ" },
  { name: "Guilherme", location: "Campos dos Goytacazes - RJ" },
  { name: "Vitor", location: "Guamaré - RN" },
  { name: "Daniel", location: "João Pessoa - PB" },
  { name: "Ronaldo", location: "Praia Grande - SP" },
  { name: "Kawann", location: "São José de Ribamar - MA" },
  { name: "Vinicius", location: "Duque de Caxias - RJ" },
  { name: "Daniel", location: "Petrolina - PE" },
  { name: "Alexsandro", location: "São Paulo - SP" },
  { name: "Everton", location: "Marília - SP" },
  { name: "André", location: "Pindamonhangaba - SP" },
  { name: "Edilson", location: "Itapecerica da serra - SP" },
  { name: "Uriel", location: "Monte Alto - SP" },
  { name: "Vitor", location: "Araucária - PR" },
  { name: "Wellington", location: "Votorantim - SP" },
  { name: "Clayton", location: "Lagarto - SE" },
  { name: "Jose", location: "Jucás - CE" },
  { name: "Luciano", location: "Porto Alegre - RS" },
  { name: "José", location: "Fortaleza - CE" },
  { name: "Mauro", location: "Belo Horizonte - MG" },
  { name: "Marcelo", location: "Itarema - CE" },
  { name: "Daniel", location: "Rondonópolis - MT" },
  { name: "Luiz", location: "Salvador - BA" },
  { name: "Rafael", location: "Caetité - BA" },
  { name: "Genilson", location: "São Luís - MA" },
  { name: "José", location: "Abaetetuba - PA" },
  { name: "Washington", location: "Volta Redonda - RJ" },
  { name: "Victor", location: "Itabira - MG" },
  { name: "Thiago", location: "Caçador - SC" },
  { name: "Alexandre", location: "Caçador - SC" },
  { name: "Wisley", location: "Currais Novos - RN" },
  { name: "Claudio", location: "Juiz de Fora - MG" },
  { name: "Rodrigo", location: "Campestre do Maranhão - MA" },
  { name: "Everton", location: "Contagem - MG" },
  { name: "Joaquim", location: "Senador Canedo - GO" },
  { name: "Heliton", location: "Quirinópolis - GO" },
  { name: "Edvaldo", location: "Visconde do Rio Branco - MG" },
  { name: "Valdnei", location: "Camaçari - BA" },
  { name: "Rogerio", location: "Rio das Ostras - RJ" },
  { name: "Fernando", location: "Itabira - MG" },
  { name: "Marcio", location: "Serra - ES" },
  { name: "Jefferson", location: "Campo Formoso - BA" },
  { name: "Leandro", location: "Sabará - MG" },
  { name: "Marcus", location: "Carmo - RJ" },
  { name: "Hugo", location: "Angra dos Reis - RJ" },
  { name: "Fabiano", location: "Manaus - AM" },
  { name: "Joelson", location: "Feira de Santana - BA" },
  { name: "Felipe", location: "Magé - RJ" },
  { name: "Edson", location: "Córrego do Ouro - GO" },
  { name: "Alexsandro", location: "Cariacica - ES" },
  { name: "Edimilson", location: "Barueri - SP" },
  { name: "Carlos", location: "Itaguaí - RJ" },
  { name: "André", location: "Serra - ES" },
  { name: "Luiz", location: "Itapissuma - PE" },
  { name: "Alessandro", location: "São Gabriel - RS" },
  { name: "Marco", location: "Fortaleza - CE" },
  { name: "Luiz", location: "Pitangueiras - SP" },
  { name: "Jonathas", location: "Linhares - ES" },
  { name: "Márcio", location: "Macaé - RJ" },
  { name: "Rodrigo", location: "Carazinho - RS" },
  { name: "Daniel", location: "Nova Iguaçu - RJ" },
  { name: "Christian", location: "Governador Valadares - MG" },
  { name: "Reinaldo", location: "São Luís - MA" },
  { name: "Wallisson", location: "Guaraciama - MG" },
  { name: "Felipe", location: "Pedro Canário - ES" },
  { name: "Gelson", location: "Brasília - DF" },
  { name: "Cauã", location: "Brasília - DF" },
  { name: "Eduardo", location: "Volta Redonda - RJ" },
  { name: "Thalison", location: "Açailândia - MA" },
  { name: "Carlos", location: "Nova Iguaçu - RJ" },
  { name: "Fernando", location: "Caçapava - SP" },
  { name: "Eder", location: "Antônio Olinto - PR" },
  { name: "Marquediane", location: "Cascavel - PR" },
  { name: "Leandro", location: "Mossoró - RN" },
  { name: "Jonas", location: "São José de Ribamar - MA" },
  { name: "Urlei", location: "São Sebastião do Paraíso - MG" },
  { name: "Francisco", location: "Fortaleza - CE" },
  { name: "Eduardo", location: "Simões Filho - BA" },
  { name: "Erivaldo", location: "Simões Filho - BA" },
  { name: "Wanderley", location: "Macaé - RJ" },
  { name: "Abdon", location: "Nova Soure - BA" },
  { name: "Carlos", location: "Minaçu - GO" },
  { name: "Edvan", location: "Estância - SE" },
  { name: "Lucas", location: "Jaguariaíva - PR" },
  { name: "Gilson", location: "Canoas - RS" },
  { name: "Sidney", location: "Osvaldo Cruz - SP" },
  { name: "Jéssica", location: "Piracicaba - SP" },
  { name: "Gilson", location: "Ipatinga - MG" },
  { name: "Gerson", location: "Maracás - BA" },
  { name: "Deivid", location: "Rio de Janeiro - RJ" },
  { name: "Rafael", location: "Paraty - RJ" },
  { name: "Leandro", location: "Alagoinhas - BA" },
  { name: "Raphael", location: "São Bernardo do Campo - SP" },
  { name: "Kelson", location: "Jacareí - SP" },
  { name: "Cristiano", location: "Juquiá - SP" },
  { name: "Evandro", location: "Joinville - SC" },
  { name: "Victor", location: "Guarapari - ES" },
  { name: "Maxwell", location: "São José de Ribamar - MA" },
  { name: "Allan", location: "Mongaguá - SP" },
  { name: "Silvio", location: "Patrocínio - MG" },
  { name: "Erivelton", location: "Barra Mansa - RJ" },
  { name: "Anderson", location: "São Gonçalo - RJ" },
  { name: "Railson", location: "Barcarena - PA" },
  { name: "Ewerton", location: "Ponta Grossa - PR" },
  { name: "Everton", location: "Gravataí - RS" },
  { name: "Edilton", location: "Salvador - BA" },
  { name: "Virgilio", location: "Lauro de Freitas - BA" },
  { name: "Célio", location: "Várzea Paulista - SP" },
  { name: "Felipe", location: "Telêmaco Borba - PR" },
  { name: "Daniel", location: "Brusque - SC" },
  { name: "Edilson", location: "Morro Agudo - SP" },
  { name: "Marco", location: "Pará de Minas - MG" },
  { name: "Thiago", location: "Tucumã - PA" },
  { name: "Lázaro", location: "São Paulo - SP" },
  { name: "Rogério", location: "Lins - SP" },
  { name: "Albert", location: "Pojuca - BA" },
  { name: "Rian", location: "Guararapes - SP" },
  { name: "Agata", location: "Belém - PA" },
  { name: "Lucas", location: "Dois Córregos - SP" },
  { name: "Fernando", location: "Jaguariúna - SP" },
  { name: "André", location: "Jundiaí - SP" },
  { name: "Daniel", location: "Guarujá - SP" },
  { name: "Jose", location: "Tucumã - PA" },
  { name: "Murillo", location: "Goianésia - GO" },
  { name: "Edilson", location: "Sinop - MT" },
  { name: "Alanderson", location: "Duque de Caxias - RJ" },
  { name: "José", location: "Macaé - RJ" },
  { name: "Reurison", location: "Camaçari - BA" },
  { name: "Leniel", location: "Tucumã - PA" },
  { name: "Wilton", location: "Macaé - RJ" },
  { name: "Elcio", location: "Maracanaú - CE" },
  { name: "Edmilson", location: "Tucumã - PA" },
  { name: "Marcelo", location: "Pinheiral - RJ" },
  { name: "Eduardo", location: "Hortolândia - SP" },
  { name: "Ricardo", location: "Uberlândia - MG" },
  { name: "Sirilo", location: "Rio das Ostras - RJ" },
  { name: "Alessandro", location: "Divinópolis - MG" },
  { name: "Joicy", location: "Tailândia - PA" },
  { name: "Ivan", location: "Candeias - BA" },
  { name: "Ricardo", location: "Dias D'Ávila - BA" },
  { name: "Antonio", location: "Belmonte - BA" },
  { name: "Eduardo", location: "Campinorte - GO" },
  { name: "Rogério", location: "Guariba - SP" },
  { name: "Jefferson", location: "Belém - PA" },
  { name: "Elenilson", location: "Belém - PA" },
  { name: "Edney", location: "Contagem - MG" },
  { name: "Elizeu", location: "Comodoro - MT" },
  { name: "Cleudir", location: "Rio de Janeiro - RJ" },
  { name: "Aloisio", location: "Passo Fundo - RS" },
  { name: "Laudenilson", location: "Candeias - BA" },
  { name: "Cayo", location: "Manaus - AM" },
  { name: "Edenilsom", location: "Tucumã - PA" },
  { name: "Iglaydson", location: "Olinda - PE" },
  { name: "Aderson", location: "Fortaleza - CE" },
  { name: "Isael", location: "Tucuruí - PA" },
  { name: "Pedro", location: "Lagoa da Prata - MG" },
  { name: "Claudio", location: "Campos dos Goytacazes - RJ" },
  { name: "Carlos", location: "Serra - ES" },
  { name: "Elielto", location: "Dianópolis - TO" },
  { name: "Tiago", location: "Lajeado - RS" },
  { name: "Marcio", location: "Itaituba - PA" },
  { name: "Lucas", location: "Jacareí - SP" },
  { name: "Adilio", location: "Brasília - DF" },
  { name: "Elielton", location: "Santa Bárbara do Pará - PA" },
  { name: "Marcos", location: "Ibirataia - BA" },
  { name: "Antônio", location: "Barbalha - CE" },
  { name: "Vagner", location: "São Paulo - SP" },
  { name: "Juliano", location: "Várzea Paulista - SP" },
  { name: "Gamaliel", location: "Mata de São João - BA" },
  { name: "Adriano", location: "Caarapó - MS" },
  { name: "Mauro", location: "Nova Serrana - MG" },
  { name: "Hugo", location: "Itapecuru Mirim - MA" },
  { name: "Afonso", location: "Paracatu - MG" },
  { name: "Douglas", location: "Mallet - PR" },
  { name: "Uelder", location: "Teodoro Sampaio - BA" },
  { name: "Carlos", location: "Parauapebas - PA" },
  { name: "Gilvan", location: "Chapadão do Céu - GO" },
  { name: "Ricardo", location: "Paracatu - MG" },
  { name: "Murilo", location: "Cerquilho - SP" },
  { name: "Ronilton", location: "Aracruz - ES" },
  { name: "Joao", location: "Paulínia - SP" },
  { name: "José", location: "Itaú de Minas - MG" },
  { name: "Silas", location: "Visconde do Rio Branco - MG" },
  { name: "Thiago", location: "São Joaquim da Barra - SP" },
  { name: "Juerley", location: "Ribeirão das Neves - MG" },
  { name: "Bernardo", location: "Petrópolis - RJ" },
  { name: "Phelippe", location: "Petrópolis - RJ" },
  { name: "Elton", location: "Corumbá - MS" },
  { name: "Alvaro", location: "Santos - SP" },
  { name: "Lucas", location: "Campos dos Goytacazes - RJ" },
  { name: "Ricardo", location: "Assis - SP" },
  { name: "Donizete", location: "Tailândia - PA" },
  { name: "Vinicius", location: "Armação dos Búzios - RJ" },
  { name: "Marcio", location: "Porangatu - GO" },
  { name: "Lucas", location: "Pinheiral - RJ" },
  { name: "Aldo", location: "Campos dos Goytacazes - RJ" },
  { name: "Claudio", location: "Joaçaba - SC" },
  { name: "João", location: "Juiz de Fora - MG" },
  { name: "Carlos", location: "Rosário do Catete - SE" },
  { name: "Matheus", location: "Ribeirão das Neves - MG" },
  { name: "Lionel", location: "Ananindeua - PA" },
  { name: "Jose", location: "Itatiaiuçu - MG" }
];

export default function SalesNotifications() {
  const [currentSale, setCurrentSale] = useState<Sale | null>(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const showNotification = () => {
      const randomSale = sales[Math.floor(Math.random() * sales.length)];
      setCurrentSale(randomSale);
      setIsVisible(true);

      setTimeout(() => {
        setIsVisible(false);
      }, 3500);
    };

    const initialDelay = setTimeout(() => {
      showNotification();
      const interval = setInterval(showNotification, 4000);
      return () => clearInterval(interval);
    }, 2000);

    return () => clearTimeout(initialDelay);
  }, []);

  return (
    <AnimatePresence>
      {isVisible && currentSale && (
        <motion.div
          initial={{ opacity: 0, x: -100 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -100 }}
          transition={{ duration: 0.5 }}
          className="fixed bottom-20 lg:bottom-8 left-4 z-40 bg-[#0F1520] border-2 border-[#00C853] rounded-lg shadow-2xl max-w-sm"
        >
          <div className="p-4">
            <button
              onClick={() => setIsVisible(false)}
              className="absolute top-2 right-2 text-[#8B95A8] hover:text-white transition-colors"
            >
              <X className="w-4 h-4" />
            </button>

            <div className="flex items-start gap-3">
              <div className="flex-shrink-0">
                <CheckCircle2 className="w-8 h-8 text-[#00C853]" />
              </div>
              <div className="flex-1">
                <div className="text-sm text-[#8B95A8]">
                  <span className="text-white font-semibold">{currentSale.name}</span> de{' '}
                  <span className="text-white">{currentSale.location}</span> se tornou nosso aluno
                </div>
                <div className="text-xs text-[#8B95A8] mt-1">agora mesmo</div>
              </div>
            </div>
          </div>
          <div className="h-1 bg-[#00C853] rounded-b-lg animate-shrink-width"></div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
